language: rust

rust:
  - stable
  - nightly

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then rustup component add clippy; fi

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then cargo fmt --all -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then cargo clippy --all --all-targets -- -D clippy::all; fi
  - cargo test --all -- --nocapture
