[package]
name = "consensus"
version = "6.2.0"
authors = ["whfuyn <whfuyn@outlook.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
git-version = "0.3.4"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v6.2.0" }
tonic = "0.5"
toml = "0.5.8"
rand = "0.8.3"
slog = "2.7.0"
sloggers = "1.0.1"
crossbeam = "0.8.0"
hex = "0.4.3"
raft = { git = "https://github.com/whfuyn/raft-rs", version = "0.6.0", default-features = false, features = ["prost-codec"] }
prost = "0.8.0"
tokio = { version = "1.5", features = ["fs", "io-util", "rt", "macros"] }
anyhow = "1"
thiserror = "1.0.24"
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"
bytes = "1.0.1"
backtrace = "0.3"

[dev-dependencies]
tempfile = "3.2.0"
