[package]
name = "consensus"
version = "6.4.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["cargo"] }
tonic = "0.5" 
toml = "0.5"
rand = "0.8"
# `release_max_level_trace` enables configuring log level at runtime.
slog = { version = "2.7.0", features = ["release_max_level_trace"] }
sloggers = "1.0.1"
log = "0.4"
hex = "0.4"
raft = { git = "https://github.com/whfuyn/raft-rs", version = "0.6.0", default-features = false, features = ["prost-codec"] }
prost = "0.8"
tokio = { version = "1.17", features = ["fs", "io-util", "rt", "macros"] }
thiserror = "1.0"
serde = "1.0"
bytes = "1.0"
backtrace = "0.3"

cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
cloud-util = { git = "https://github.com/cita-cloud/cloud-util" }

[dev-dependencies]
tempfile = "3.3"
