[package]
name = 'consensus'
version = '6.7.0-beta1'
edition = '2021'
authors = ['Rivtower Technologies <contact@rivtower.com>']

[dependencies]
tonic = '0.9'
toml = '0.7'
rand = '0.8'
sloggers = '2.1.1'
log = '0.4'
hex = '0.4'
prost = '0.11'
serde = '1.0'
bytes = '1.4'
tower = '0.4.13'
cloud-util = '=0.7.0-beta1'
cita_cloud_proto = '=6.7.0-beta1'

[dependencies.clap]
version = '4.2'
features = ['cargo']

[dependencies.slog]
version = '2.7.0'
features = ['release_max_level_trace']

[dependencies.raft]
git = 'https://github.com/cita-cloud/raft-rs'
version = '0.6.0'
default-features = false
features = ['prost-codec']

[dependencies.tokio]
version = '1.27'
features = [
    'fs',
    'io-util',
    'rt',
    'macros',
]

[dev-dependencies]
tempfile = '3.5'
