[package]
name = "consensus"
version = "4.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
clap = "3.0.0-beta.2"
git-version = "0.3.4"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v4.0.0" }
tonic = "0.4.1"
prost = "0.7.0"
bytes = "1.0.1"
protobuf = { version = "2.22.1", features = ["with-bytes"] }
tokio = { version = "1.4.0", features = ["full"] }
rand = "0.8.3"
serde = "1.0.125"
serde_derive = "1.0.125"
toml = "0.5.8"
raft = { git = "https://github.com/tikv/raft-rs", version = "0.6.0-alpha" }
slog = "2.7.0"
slog-envlogger = { version = "2.2.0" }
slog-stdlog = { version = "4.1.0" }
slog-term = { version = "2.8.0" }
slog-async = "2.6.0"
crossbeam = "0.8.0"
hex = "0.4.3"
