[package]
name = "consensus"
version = "0.1.0"
authors = ["whfuyn <whfuyn@outlook.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
clap = "3.0.0-beta.2"
git-version = "*"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
tonic = "*"
prost = "*"
bytes = "*"
protobuf = { version = "*", features = ["with-bytes"] }
tokio = { version = "*", features = ["full"] }
rand = "*"
serde = "*"
serde_derive = "*"
toml = "*"
raft = { git = "https://github.com/tikv/raft-rs", version = "0.6.0-alpha"}
slog = "*"
slog-envlogger = { version = "*" }
slog-stdlog = { version = "*" }
slog-term = { version = "*" }
slog-async = "*"
crossbeam = "*"
hex = "*"
