[package]
name = "consensus"
version = "6.3.3"
authors = ["whfuyn <whfuyn@outlook.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.1.6", features = ["cargo"] }
git-version = "0.3.4"
tonic = "0.5" 
toml = "0.5.8"
rand = "0.8.3"
# `release_max_level_trace` enables configuring log level at runtime.
slog = { version = "2.7.0", features = ["release_max_level_trace"] }
sloggers = "1.0.1"
# slog unable to compile because the latest version: 0.4.16 modifies the interface, todo delete
log = "=0.4.14"
hex = "0.4.3"
raft = { git = "https://github.com/whfuyn/raft-rs", version = "0.6.0", default-features = false, features = ["prost-codec"] }
prost = "0.8.0"
tokio = { version = "1.5", features = ["fs", "io-util", "rt", "macros"] }
anyhow = "1"
thiserror = "1.0.24"
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"
bytes = "1.0.1"
backtrace = "0.3"

cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
cloud-util = { git = "https://github.com/cita-cloud/cloud-util" }

[dev-dependencies]
tempfile = "3.2.0"
