[package]
name = "consensus"
version = "6.6.2"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["cargo"] }
tonic = "0.8"
toml = "0.5"
rand = "0.8"
# `release_max_level_trace` enables configuring log level at runtime.
slog = { version = "2.7.0", features = ["release_max_level_trace"] }
sloggers = "2.1.1"
log = "0.4"
hex = "0.4"
raft = { git = "https://github.com/cita-cloud/raft-rs", version = "0.6.0", default-features = false, features = ["prost-codec"] }
prost = "0.11"
tokio = { version = "1.21", features = ["fs", "io-util", "rt", "macros"] }
serde = "1.0"
bytes = "1.2"
backtrace = "0.3"
tower = "0.4.13"

cloud-util = { package = "cloud-util", git = "https://github.com/cita-cloud/cloud-common-rs.git" }
cita_cloud_proto = { package = "cita_cloud_proto", git = "https://github.com/cita-cloud/cloud-common-rs.git" }

[dev-dependencies]
tempfile = "3.3"
